### ISSUE TITLE
axis control

### ISSUE THREAD

**Issue by antimodular** [bakercp/ofxIpVideoGrabber#10] opened 2015-03-16 19:08 UTC
i have an axis camera that has pan till zoom controls view their web interfaces.
they also give access to pan till zoom via their "AXIS Media Control" SDK:
http://www.axis.com/techsup/cam_servers/dev/activex.htm

```
  AMC.MediaType:='mjpeg';
  AMC.MediaURL:='http://10.0.1.10/axis-cgi/mjpg/video.cgi';
  AMC.MediaUserName:='root';
  AMC.MediaPassword:='myPassw';

  AMC.PTZControlURL:='http://10.0.1.10/axis-cgi/com/ptz.cgi';
```
and i assume after one is logged on http://10.0.1.10/axis-cgi/com/ptz.cgi?zoom=2 would give it the control i want.

i do get a video feed with your addon.

do you see any chance of doing this without their SDK.
I am not on windows.

**Comment by bakercp** [comment] 2015-03-16 19:31
Hey there, yes, I've done this before -- although it was in Java.  But it could be updated to use ofxHTTP (or another http client) to issue the various calls.  A good starting point might be:

https://github.com/themaw/mawLib/blob/master/src/mxj/trunk/mawLib-mxj/src/maw/jit/ipcam/PTZCameraControl.java

which I wrote for another project.  All of it is simply constructing HTTP commands ...

The video stream and the PTZ control are separate.  You might even be able to use the standard ofLoadURL to do it, but ofxHTTP has a lot more advanced features for logging in w/ username pass, etc.  Keep me posted!

**Comment by bakercp** [comment] 2015-03-16 19:33
Also, by the way, when I wrote that I just reverse-engineered the javascript file that the Axis cam served up.  It may or may not be the exact commands used by your camera, but it's probably pretty similar.

**Comment by antimodular** [comment] 2015-03-17 14:16
thanks. looks great.
i did manage to get control using ofHttpUtils

also found this doc with lots of commands:
http://www.axis.com/techsup/cam_servers/dev/cam_http_api_2.php#api_blocks_ptz

**Comment by bakercp** [comment] 2016-03-10 20:16
Closing this as it's not a bug.  Currently there aren't plans to add camera control signals.  If I were to do this, I would use ofxHTTP which can make pretty extensible / configurable HTTP clients.

**Closed by bakercp** 2016-03-10 20:16 UTC
